jix_sms.daily.sms:
  type: config_object
  label: 'JIR SMS Settings'
  mapping:
    number.daily.jobs:
      type: number
      label: 'Number of jobs'
    mtarget.ftp:
      host:
        type: textfield
        label: 'Host'
      port:
        type: number
        label: 'Port'
      username:
        type: textfield
        label: 'Username'
      password:
        type: textfield
        label: 'Password'